name: the_weather_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  scrollable_positioned_list: ^0.2.3
  flutter_svg: ^1.0.0
  auto_size_text: ^3.0.0
  carousel_slider: ^4.0.0
#  mapbox_search: ^3.0.1+2
  geolocator: ^8.0.1
  flutter_mapbox_autocomplete: ^2.0.0
  shimmer: ^2.0.0
  easy_localization: ^3.0.0
  shared_preferences: ^2.0.17
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter_bloc: ^7.1.0
  get_it: ^7.2.0
  firebase_analytics: ^10.2.0
  firebase_core: ^2.9.0
  url_launcher: ^6.1.10
  meta_seo: ^3.0.5
  timezone: ^0.9.2
  location: ^4.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  mocktail: ^0.3.0
  flutter_native_splash: ^2.2.19
flutter_launcher_icons:
  image_path: "assets/appIcon/01n_1024x1024.png"
  image_path_android: "assets/appIcon/01n_1024x1024.png"
#  image_path_ios: "assets/images/icon-1024x1024.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: false # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "#060D26" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/appIcon/01n_1024x1024.png" # only available for Android 8.0 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
#  remove_alpha_ios: true
#  background_color_ios: "#ffffff"
  web:
    generate: true
    image_path: "assets/appIcon/01n_1024x1024.png"
    background_color: "#060D26"
    theme_color: "#060D26"
  windows:
    generate: false
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: false



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/dashboard_icons/
    - assets/weather_3d/
    - assets/locales/
    - assets/appIcon/
#    - assets/VisualCrossingFolder/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
